# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VkModule', '0002_changegroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='group_name',
            field=models.TextField(default=b'No name'),
        ),
        migrations.AlterField(
            model_name='changegroup',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 13)),
        ),
    ]
