# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-21 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VkModule', '0003_auto_20161113_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='comment',
            field=models.TextField(default=b'-'),
        ),
        migrations.AlterField(
            model_name='changegroup',
            name='date',
            field=models.DateField(default=datetime.date(2017, 1, 21)),
        ),
    ]
