# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VkModule', '0004_auto_20161113_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='group_name',
            field=models.TextField(default=b'No name'),
        ),
    ]
