# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VkModule', '0004_auto_20170121_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changegroup',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 16)),
        ),
    ]
