# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VkModule', '0005_auto_20170216_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changegroup',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
